name: Docker Build/Publish Image

on:
  workflow_dispatch:
    inputs:
      ngVersion:
        description: 'Hyperion NG Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/arm/v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: ng_version=${{ github.event.inputs.ngVersion }}
          file: ./Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: romrider/hyperion-ng:${{ github.event.inputs.ngVersion }}
